-- List all books with price greater than 80,000 VND (basic SELECT + WHERE)
SELECT * FROM Books WHERE Price > 80000;
-- Find books whose title contains “Kiều” (string pattern matching)
SELECT * FROM Books WHERE Title LIKE '%Kiều%';
-- Show all orders placed in the year 2026 (date filtering)
SELECT * FROM Orders WHERE YEAR(OrderDate) = 2026;
-- Count total number of books in stock (aggregate without GROUP BY)
SELECT SUM(Stock) AS TotalStock FROM Books;
-- List customer names and phone numbers, sorted by name (ORDER BY)
SELECT Name, Phone FROM Customers ORDER BY Name;
-- Display order details with book titles and customer names (JOIN three tables)
SELECT o.OrderID, c.Name AS CustomerName, b.Title, od.Quantity, od.UnitPrice
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Books b ON od.BookID = b.BookID;
-- Total revenue generated by each book (GROUP BY + SUM)
SELECT b.Title, SUM(od.Quantity * od.UnitPrice) AS Revenue
FROM Books b
JOIN OrderDetails od ON b.BookID = od.BookID
GROUP BY b.BookID, b.Title
ORDER BY Revenue DESC;
-- Number of orders per customer (GROUP BY + COUNT)
SELECT c.Name, COUNT(o.OrderID) AS OrderCount
FROM Customers c
LEFT JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, c.Name;
-- Employees who have never processed any order (LEFT JOIN + IS NULL)
SELECT e.Name, e.Position
FROM Employees e
LEFT JOIN Orders o ON e.EmployeeID = o.EmployeeID
WHERE o.OrderID IS NULL;
-- The most expensive book (subquery with MAX)
SELECT * FROM Books
WHERE Price = (SELECT MAX(Price) FROM Books);
-- Books that have never been sold (NOT EXISTS)
SELECT * FROM Books b
WHERE NOT EXISTS (
    SELECT 1 FROM OrderDetails od WHERE od.BookID = b.BookID
);
-- Customer who spent the most money (ORDER BY LIMIT – alternative to subquery)
sql
SELECT c.CustomerID, c.Name, SUM(o.TotalAmount) AS TotalSpent
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, c.Name
ORDER BY TotalSpent DESC
LIMIT 1;
-- Total sales per employee (including those with zero sales)
SELECT e.Name, COALESCE(SUM(o.TotalAmount), 0) AS TotalSales
FROM Employees e
LEFT JOIN Orders o ON e.EmployeeID = o.EmployeeID
GROUP BY e.EmployeeID, e.Name;
-- Average number of books per order (using subquery in FROM)
SELECT AVG(BookCount) AS AvgBooksPerOrder
FROM (
    SELECT OrderID, SUM(Quantity) AS BookCount
    FROM OrderDetails
    GROUP BY OrderID
) AS OrderSummary;
-- Orders where total amount exceeds the average order total (subquery in WHERE)
SELECT * FROM Orders
WHERE TotalAmount > (SELECT AVG(TotalAmount) FROM Orders);
-- Books with stock level below 10 (low stock alert)
SELECT Title, Stock, Price
FROM Books
WHERE Stock < 10
ORDER BY Stock ASC;
-- Top 3 best-selling books by quantity (aggregate + LIMIT)
SELECT b.Title, SUM(od.Quantity) AS TotalSold
FROM Books b
JOIN OrderDetails od ON b.BookID = od.BookID
GROUP BY b.BookID, b.Title
ORDER BY TotalSold DESC
LIMIT 3;
-- Monthly revenue for the year 2026 (date formatting + GROUP BY)
SELECT DATE_FORMAT(OrderDate, '%Y-%m') AS Month, SUM(TotalAmount) AS Revenue
FROM Orders
WHERE YEAR(OrderDate) = 2026
GROUP BY DATE_FORMAT(OrderDate, '%Y-%m')
ORDER BY Month;
-- List all customers who bought the book “Nhà Giả Kim” (subquery with IN)
SELECT DISTINCT c.Name, c.Phone
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
WHERE o.OrderID IN (
    SELECT OrderID FROM OrderDetails od
    JOIN Books b ON od.BookID = b.BookID
    WHERE b.Title = 'Nhà Giả Kim'
);
-- Show each book’s total sold quantity and remaining stock, along with a status flag (CASE statement)
SELECT b.Title,
       b.Stock AS Remaining,
       COALESCE(SUM(od.Quantity), 0) AS Sold,
       CASE
           WHEN COALESCE(SUM(od.Quantity), 0) > 5 THEN 'Popular'
           WHEN COALESCE(SUM(od.Quantity), 0) > 0 THEN 'Moving'
           ELSE 'Slow'
       END AS SalesStatus
FROM Books b
LEFT JOIN OrderDetails od ON b.BookID = od.BookID
GROUP BY b.BookID, b.Title, b.Stock;
